name: canteen_frontend_seller
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  crop_your_image: ^2.0.0
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.5.2
  get_it: ^9.2.0
  go_router: ^17.0.0
  image_picker: ^1.2.1
  json_annotation: ^4.9.0
  json_serializable: ^6.0.1
  web_socket_channel: ^3.0.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
